---

- name: RedHat8+ | Check available repo
  ansible.builtin.command: ls /etc/yum.repos.d/
  changed_when: false

- name: RedHat9 | Enable PowerTools repo
  ansible.builtin.command:  # noqa no-changed-when
    cmd: dnf config-manager --enable crb
  become: yes
  when:
    - ansible_distribution_major_version | int == 9

- name: RedHat8 | Enable PowerTools repo
  ansible.builtin.command:  # noqa no-changed-when
    cmd: dnf config-manager --set-enabled powertools
  become: yes
  when:
    - ansible_distribution_major_version | int == 8

- name: Check available repositories - list
  ansible.builtin.command: ls /etc/yum.repos.d/
  changed_when: false
  failed_when: false

- name: Check available repositories
  ansible.builtin.command: dnf repolist
  changed_when: false
  when:
    - ansible_distribution_major_version | int >= 8

- name: RedHat8+ | Ensure libarchive is present - cmake archive_write_add_filter_zstd undefined symbol
  ansible.builtin.package:
    name: libarchive
    state: present
  when:
    - ansible_distribution_major_version | int >= 8
