---

- name: Verify
  hosts: tlsh
  pre_tasks:
    - name: Ubuntu 12.04 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python2.7/dist-packages/tlsh.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 12)
    - name: Ubuntu 14.04 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python3.4/dist-packages/tlsh.cpython-34m-x86_64-linux-gnu.so
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 14)
    - name: Ubuntu 16.04 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python3.5/dist-packages/tlsh.cpython-35m-x86_64-linux-gnu.so
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 16)
    - name: Ubuntu 18.04 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python3.6/dist-packages/tlsh.cpython-36m-x86_64-linux-gnu.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 18)
    - name: Ubuntu 20.04 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python3.8/dist-packages/tlsh.cpython-38-x86_64-linux-gnu.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 20)
    - name: Ubuntu 22.04 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python3.10/dist-packages/tlsh.cpython-310-x86_64-linux-gnu.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 22)
    - name: Ubuntu 24.04 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python3.12/dist-packages/tlsh.cpython-312-x86_64-linux-gnu.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] | int == 24)
    - name: Centos 6 | set fact
      ansible.builtin.set_fact:
        libso: /usr/lib64/python2.7/site-packages/tlsh.so
      when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 6)
    - name: Centos 7 | set fact
      ansible.builtin.set_fact:
        libso: /usr/lib64/python3.4/site-packages/tlsh.cpython-34m.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3.4
      when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 7)
    - name: Centos 8 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib64/python3.6/site-packages/tlsh.cpython-36m-x86_64-linux-gnu.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3
      when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 8)
    - name: RedHat 9 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib64/python3.9/site-packages/tlsh.cpython-39m-x86_64-linux-gnu.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3
      when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] | int == 9)
    - name: Debian 12 | set fact
      ansible.builtin.set_fact:
        libso: /usr/local/lib/python3.11/dist-packages/tlsh.cpython-311-x86_64-linux-gnu.so
        python_test: /opt/tools/tlsh/Testing/python_test.sh python3
      when: (ansible_facts['distribution'] == "Debian" and ansible_facts['distribution_major_version'] | int == 12)

  tasks:
    - name: Check TLSH files
      ansible.builtin.command: find /opt/tools/tlsh/lib /usr/local/lib /usr/local/lib64 /usr/lib64 -iname '*tlsh*'
      changed_when: false
      failed_when: false

    - name: Ensure /opt/tools/tlsh/lib/libtlsh.a file is present
      ansible.builtin.stat:
        path: /opt/tools/tlsh/lib/libtlsh.a
      register: liba
    - name: Validate libtlsh.a present
      ansible.builtin.assert:
        that: liba.stat.exists and liba.stat.size != 0

    - name: Ensure /opt/tools/tlsh/lib/libtlsh.so file is present
      ansible.builtin.stat:
        path: /opt/tools/tlsh/lib/libtlsh.so
      register: libso
    - name: Validate libtlsh.so present
      ansible.builtin.assert:
        that: libso.stat.exists and libso.stat.size != 0
      when: false

    - name: Tlsh version
      ansible.builtin.command: /opt/tools/tlsh/bin/tlsh_pattern -version
      changed_when: false
      register: ver
    - name: Validate version command
      ansible.builtin.assert:
        that:
          - "'compact hash 1 byte checksum sliding_window=' in ver.stdout"
          - ver.rc == 0

    - name: Tlsh test
      ansible.builtin.command: /opt/tools/tlsh/Testing/test.sh
      changed_when: false
      register: test
    - name: Validate test command
      ansible.builtin.assert:
        that:
          - "'passed' in test.stdout"
          - test.rc == 0

    - name: Tlsh test extended
      ansible.builtin.command: /opt/tools/tlsh/Testing/test.sh -xlen
      changed_when: false
      ignore_errors: true
      register: test2
    - name: Validate test command - extended
      ansible.builtin.assert:
        that:
          - "'passed' in test2.stdout"
          - "'passed all example data tests' in test2.stdout"
          - test2.rc == 0
      failed_when: false

    - name: Find Tlsh so
      ansible.builtin.command: find /usr/local/lib* /usr/lib* /opt -iname 'tlsh*.so'
      changed_when: false
      failed_when: false
      register: test3
    - name: Tlsh python test
      ansible.builtin.command: "{{ python_test }}"
      changed_when: false
      register: test3
    - name: Validate python test command
      ansible.builtin.assert:
        that:
          - "'passed' in test3.stdout"
          - test3.rc == 0
